-- CreateTable
CREATE TABLE `prevent_gambling_forms` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `agency` VARCHAR(191) NOT NULL,
    `agency_id` INTEGER NULL,
    `name` VARCHAR(191) NULL,
    `openday` VARCHAR(191) NOT NULL,
    `eval_date` VARCHAR(191) NOT NULL,
    `ptcprogram` VARCHAR(191) NULL,
    `prevent_contents` VARCHAR(191) NULL,
    `pv` VARCHAR(191) NULL,
    `past_stress_experience` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `prevent_gambling_seq` INTEGER NULL,
    `sex` VARCHAR(191) NULL,
    `age` VARCHAR(191) NULL,
    `residence` VARCHAR(191) NULL,
    `job` VARCHAR(191) NULL,
    `score1` VARCHAR(191) NULL,
    `score2` VARCHAR(191) NULL,
    `score3` VARCHAR(191) NULL,
    `score4` VARCHAR(191) NULL,
    `score5` VARCHAR(191) NULL,
    `score6` VARCHAR(191) NULL,
    `score7` VARCHAR(191) NULL,
    `score8` VARCHAR(191) NULL,
    `score9` VARCHAR(191) NULL,
    `score10` VARCHAR(191) NULL,
    `score11` VARCHAR(191) NULL,
    `score12` VARCHAR(191) NULL,
    `score13` VARCHAR(191) NULL,
    `score14` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
