import { gql } from '@apollo/client';

// 엑셀 다운로드용 데이터 쿼리
export const GET_EXCEL_PROGRAM_LIST = gql`
  query GetExcelProgramList($openday: String, $endday: String) {
    excelProgramList(openday: $openday, endday: $endday) {
      sheet1 {
        year
        month
        day
        dayOfWeek
        stayDays
        reservationType
        groupName
        region
        businessCategory
        mineArea
        orgNature
        partType
        partForm
        serviceType
        participantCount
        totalPersonDays
        infantCount
        elementaryCount
        middleCount
        highCount
        adultCount
        elderlyCount
        reservationManager
        operationManager
        programCount
        day2Rooms
        day4Rooms
        mealCount
        totalBudget
      }
      sheet2 {
        id
        date
        dayOfWeek
        groupName
        programName
        place
        startTime
        endTime
        timeSlot
        instructorName
        assistantName
        helperName
        businessCategory
        totalCount
        programType
        reservation_date
        start_date
        group_name
        program_name
        place_name
        start_time
        end_time
        instructor_name
        assistant_name
        helper_name
        notes
        venue
        manager
        special_notes
        institution_name
      }
      sheet3 {
        sequenceNumber
        year
        month
        day
        dayOfWeek
        stayDays
        groupName
        region
        mineArea
        businessCategory
        orgNature
        isMou
        partType
        partForm
        serviceType
        participantCount
        totalPersonDays
        elementaryCount
        middleCount
        highCount
        adultCount
        elderlyCount
        operationManager
        programCount
        day2Rooms
        day4Rooms
        mealTotalCount
        totalExpense
        totalRevenue
      }
      sheet4 {
        sequenceNumber
        year
        month
        day
        groupName
        businessCategory
        categoryName
        programName
        placeName
        participants
        instructorName
        instructorType
        instructorSatisfaction
        programComposition
        effectiveness
      }
      sheet5 {
        sequenceNumber
        instructorName
        instructorType
        categoryName
        programName
        lectureCount
        totalParticipants
        instructorSatisfaction
        programComposition
        effectiveness
        averageScore
      }
      sheet6 {
        no
        category
        program_name
        instructor_name
        instructor_type
        run_count
        survey_participants
        satisfaction_instructor
        satisfaction_program
        satisfaction_effect
        satisfaction_avg
      }
      sheet7 {
        sequenceNumber
        year
        month
        day
        groupName
        businessType
        participantCount
        accommodationSatisfaction
        programPlaceSatisfaction
        outdoorAccommodationSatisfaction
        operationSatisfaction
        mealSatisfaction
        facilityAverage
      }
      sheet8 {
        sequenceNumber
        year
        month
        day
        groupName
        participantCount
        category
        healingEffectTotal
        healingEffectAverage
      }
      sheet9 {
        sequenceNumber
        year
        month
        day
        groupName
        participantCount
        category
        preventionEffectTotal
        preventionEffectAverage
      }
      sheet10 {
        sequenceNumber
        year
        month
        day
        groupName
        participantCount
        category
        counselingTherapyTotal
        counselingTherapyAverage
      }
      sheet11 {
        sequenceNumber
        year
        month
        day
        groupName
        participantCount
        category
        autonomicNervousActivity
        autonomicNervousBalance
        stressIndexLevel
        stressIndex
        ratio
      }
    }
  }
`; 